services:
  dirsrv:
    build:
      context: .
      dockerfile: Containerfile-dev
      args:
        CUSTOM_CRT_URL: ${CUSTOM_CRT_URL}
    hostname: dirsrv
    container_name: dirsrv
    ports:
      - "3389:3389"
      - "3636:3636"
    init: true
    entrypoint: ["sleep", "infinity"]
    environment:
      CC: gcc
      CXX: g++
      CFLAGS: "-O2 -g"
      CXXFLAGS: ${CXXFLAGS}
      LDFLAGS: ${LDFLAGS}
      DS_DM_PASSWORD: password
      DS_SUFFIX_NAME: dc=example,dc=com
      DS_BACKEND_NAME: example
    volumes:
      - ./:/389-ds-base